# Creation date:        2022-01-15
# Contributors:         Jean-Marc Andreoli
# Language:             python
# Purpose:              Doc generation script
#
# Fill in the following variables and save as Makefile. Alternatively
# you can set these variables from the command line, and also
# from the environment for the first two.
#
SPHINXOPTS    ?=
SPHINXBUILD   ?=
SOURCEDIR     = .
BUILDDIR      = _build
# needed for _resource
RSCMAKE       =
SOFFICE       = soffice
#
# There should be no need to change below this line
#--------------------------------------------------------------------------------------------------
#
# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
#
.PHONY: help Makefile
#
rsc: $(addprefix _resource/mod_,cache.out cache-timeline.png cache-workflow.png polling.out html.out) ;
#
rsc-clean:
	@echo Removing everything under _resource ...
	@rm -rf _resource/*
#
_resource/%.out:: %.py
	@echo Generating $@
	@export PYTHONPATH=$(realpath ../.pythonpath):$(PYTHONPATH); ${RSCMAKE} $< $@
#
_resource/%.png:: %.odg
	@echo Generating $@ ...
	@${SOFFICE} --headless --convert-to png --outdir _resource $<
#
# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
